# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

# A starter config to use with Recyclarr. Most values are set to "reasonable defaults". Update the
# values below as needed for your instance. You will be required to update the API Key and URL for
# each instance you want to use.
#
# Many optional settings have been omitted to keep this template simple.
#
# For more details on the configuration, see the Configuration Reference on the wiki here:
# https://github.com/recyclarr/recyclarr/wiki/Configuration-Reference

# Configuration specific to Sonarr
sonarr:
  sonarr:
    base_url: http://INSERT_HOST:8990
    api_key: INSERT_API_KEY
            
    delete_old_custom_formats: true
    replace_existing_custom_formats: true

    # Include Configuration
    include:
      - config: sonarr-hd.yaml

    # Media Naming Configuration
    media_naming:
      series: plex-tvdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    # Quality Definition Configuration
    quality_definition:
      type: series
      preferred_ratio: 0.05

    quality_profiles:
      - name: 1080p Balanced
        min_format_score: 0
        reset_unmatched_scores:
          enabled: false
        upgrade:
          allowed: true
          until_quality: 1080p Balanced
          until_score: 5000
        score_set: default
        quality_sort: top
        qualities:
          - name: 1080p Balanced
            qualities:
              - WEBDL-1080p
              - Bluray-1080p
          - name: 1080p Fallback
            qualities:
              - HDTV-1080p
              - WEBRip-1080p
          - name: 720p Balanced
            qualities:
              - Bluray-720p
              - WEBDL-720p
          - name: 720p Fallback
            qualities:
              - WEBRip-720p
              - HDTV-720p
          - name: SD Balanced
            qualities:
              - Bluray-576p
              - Bluray-480p
              - WEBDL-480p
          - name: SD Fallback
            qualities:            
              - WEBRip-480p
              - SDTV
              - DVD
          #- name: Last Resort
          #  qualities:            
          #    - Bluray-1080p Remux
          #    - Unknown
